users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL 
    groups: user, admin 
    home: /home/ubuntu
    shell: /bin/bash 
    ssh_authorized_keys: # Public key (your-key.pub)
ssh_pwauth: false 
disable_root: false
package_update: true  
packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - mariadb-server
