#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL 
    groups: user, admin 
    home: /home/ubuntu
    shell: /bin/bash 
    ssh_authorized_keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFvxB6AIaJa3UP9YxvwpiDm5bhxDYlzjqLSpQ8eAyu7rPmMOkIc74e5/gu8kPhbtcaX+bfUkEN8XMNoes2O5E9ujsDm4c20HmDN13Hc16qyvQZVULqpTIkp81YxjZAhmmkAYm9gxxHmVMPhCkAjD+ZiRE4dOqK2WsQKT6f8jopP0WLiGdBgyDR1yUMYqF9KmmtaAPKtLZTPzP51nsLsGN+kVe8hQwbACeThcfzZfEah04sTt5s2DYT+BAvamUX050WlRGk5WwvpHp/D46+t7ehnzHbcvbLXwjdtnZ/usVqeI/6Z5p2cfZJR35MAuThbDcIk6kCy//X2Wt3iA6NFQKkuJ1e5+WMHugWEwxC+kBDg0xjUTbOuKdi5g8chti2Wh/QplH6WqJTvI+51UfUXaPV3SfFcBqSmn+bhXDKasiNBRbFvAR557I8rdumlvo9hhme7WBY569PCWc0ixAjLzEAvWGeLGGaPf1SWf7l/R4W/3ju5vnXeGb85nL/GKBLQKaO1m0mBZ5I7REsigwRavNNYk67y/BlIO/2JoTftrAI0SfDnPPqvynfpfdlnyFZ6q7IY5YeGE4ffQoBX3nQFfl9TzRFgbYebxa8LrrcMAil+rpbA/23e/x35fA0YoieuZ1SLQQZjJ3iH/CRJOkhhXnAk35epPa586AdXuVulgCKfQ== sxpersxnic@sxnic
ssh_pwauth: false  
disable_root: false
package_update: true  
packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2