#cloud-config
users:
  - name: ubuntu 
    sudo: ALL=(ALL) NOPASSWD:ALL 
    groups: user, admin 
    home: /home/ubutntu
    shell: /bin/bash 
    ssh_authorized_keys: ssh-key XXXXXXXX aws-key
ssh_pwauth: false 
disable_root: false 
package_update: true 
packages:
  - curl
  - wget
runcmd: 
write_file: 
